import validator from 'validator'
import bcrypt from 'bcrypt'
import userModel from '../models/userModel.js'
import jwt from 'jsonwebtoken'
import {v2 as cloudinary} from 'cloudinary'
import doctorModel from '../models/doctorModel.js'
import appointmentModel from '../models/appointmentModel.js'

//API to register user
const registerUser = async(req,res) =>{
    try {
        const {name,email,password} = req.body

        if (!name || !password || !email) {
            return res.json({success:false, message:'All fields are required'})
        }
        //validating email
        if (!validator.isEmail(email)) {
            return res.json({success:false, message:"Invalid email"})
        }
        //validating strong password
        if (password.length < 8) {
            return res.json({success:false, message:"Password must be at least 8 characters long"})
        }
        //hashing user password
        const salt = await bcrypt.genSalt(10)
        const hashedPassword = await bcrypt.hash(password,salt)

        const userData = {
            name,email,password:hashedPassword
        }
        const newUser = new userModel(userData)
        const user = await newUser.save()
        //_id is generated by mongoDB
        const token = jwt.sign({id:user._id},process.env.JWT_SECRET)
        res.json({success:true, message:'User registered successfully',token})
    } catch (error) {
        console.log(error)
        res.json({success:false, message:error.message})
    }
}
//API to use login
const loginUser = async(req,res)=>{
    try {
        const {email,password}= req.body
        const user = await userModel.findOne({email})
        if(!user){
            return res.json({success:false, message:'User not found'})
        }
        const isMatch = await bcrypt.compare(password,user.password)
        if (isMatch) {
            const token = jwt.sign({id:user._id}, process.env.JWT_SECRET)
            res.json({success:true, message:'User logged in successfully',token})
        }else{
            res.json({success:false, message:'Invalid credentials'})
        }
    } catch (error) {
        console.log(error)
        res.json({success:false, message:error.message})
    }
}

//API to get user profile data
const getProfile = async(req,res)=>{
    try{
        const userId = req.userId
        const userData = await userModel.findById(userId).select('-password')

        res.json({success:true, userData})

    }catch(error){
        console.log(error)
        res.json({success:false, message:error.message})
    }
}
//API to update profile
const updateProfile = async(req,res)=>{
    try {
        const userId = req.userId  // ✅ from middleware, not req.body
        const {name,phone,address,dob,gender} = req.body
        const imageFile = req.file

        if (!name || !phone || !address || !dob || !gender) {
            return res.json({success:false, message:'All fields are required'})
        }

        await userModel.findByIdAndUpdate(userId,{name,phone,address:JSON.parse(address),dob,gender})

        if(imageFile){
            const imageUpload = await cloudinary.uploader.upload(imageFile.path,{resource_type:"image"})  // ✅ .upload()
            const imageURL = imageUpload.secure_url
            await userModel.findByIdAndUpdate(userId,{image:imageURL})
        }

        res.json({success:true, message:'Profile updated successfully'})
        
    } catch (error) {
        console.log(error)
        res.json({success:false, message:error.message})
    }
}

//API to book appointment
const bookAppointment = async (req, res) => {
  try {
    const { docId, slotDate, slotTime } = req.body;
    const userId = req.userId;

    const docData = await doctorModel
      .findById(docId)
      .select("-password");

    if (!docData) {
      return res.json({
        success: false,
        message: "Doctor not found",
      });
    }

    let slots_booked = docData.slots_booked || {};

    // Check slot availability
    if (slots_booked[slotDate]) {
      if (slots_booked[slotDate].includes(slotTime)) {
        return res.json({
          success: false,
          message: "Slot already booked",
        });
      } else {
        slots_booked[slotDate].push(slotTime);
      }
    } else {
      slots_booked[slotDate] = [slotTime];
    }

    const userData = await userModel
      .findById(userId)
      .select("-password");

    const docDataObj = docData.toObject();
    delete docDataObj.slots_booked;

    const appointmentData = {
      userId,
      docId,
      userData,
      docData: docDataObj,
      amount: docData.fees,
      slotDate,
      slotTime,
      date: Date.now(),
      payment: false,
    };

    const newAppointment = new appointmentModel(
      appointmentData
    );

    await newAppointment.save();

    // Save updated booked slots
    await doctorModel.findByIdAndUpdate(docId, {
      slots_booked,
    });

    res.json({
      success: true,
      message: "Appointment booked successfully",
    });
  } catch (error) {
    console.log(error);
    res.json({
      success: false,
      message: error.message,
    });
  }
};

//API 4 to get user appointments 4 frontend  my-appointments page
const listAppointments = async(req,res)=>{
  try {
    const userId = req.userId
    const appointments = await appointmentModel.find({userId})

    res.json({success:true,appointments})

  } catch (error) {
    console.log(error)
    res.json({success:false, message:error.message})
  }
}
//API to cancel appointment
const cancelAppointment = async (req, res) => {
  try {
    const userId = req.userId
    const {appointmentId} = req.body

    const appointmentData = await appointmentModel.findById(appointmentId)


    //verify appointment user
    if(appointmentData.userId.toString() !== userId){   // ✅ also use .toString(), userId in DB is ObjectId
      return res.json({success:false, message:'You are not authorized to cancel this appointment'})
    }
    await appointmentModel.findByIdAndUpdate(appointmentId,{cancelled:true})
    //releasing doctor slot
    const {docId,slotDate,slotTime} = appointmentData

    const doctorData = await doctorModel.findById(docId)

    let slots_booked = doctorData.slots_booked

    slots_booked[slotDate] = slots_booked[slotDate].filter((e) => e !== slotTime)

    await doctorModel.findByIdAndUpdate(docId,{slots_booked})

    res.json({success:true, message:'Appointment cancelled successfully'})

  } catch (error) {
    console.log(error)
    res.json({success:false, message:error.message})
  }
}

export {registerUser,loginUser,getProfile,updateProfile, bookAppointment,listAppointments,cancelAppointment}